//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Личный_кабинет_сотрудника_библиотеки
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSet
    {
        public int Id { get; set; }
        public int IdBook { get; set; }
        public int IdReader { get; set; }
        public string DateDelivery { get; set; }
        public string DateReturn { get; set; }
    
        public virtual BookSet BookSet { get; set; }
        public virtual ReaderSet ReaderSet { get; set; }
    }
}
